#############################
# Xups for Hexo主题配置文件
# xinxiucan
# http://blogxinxiucan.sh1.newtouch.com/
#############################

#----------------------------
# 头部导航
#----------------------------
menu:
  home:
    name: 首页
    link: /
    icon: icon-home
  lab:
    name: 大数据
    link: /lab/
    icon: 
  about:
    name: 关于
    link: /about/
    icon: 
  comment:
    name: 留言
    link: /comment/
    icon: 


#----------------------------
# 副导航
#----------------------------
lab:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"

#----------------------------
# RS#----------------------------
rss: /atom.xml

#----------------------------
# Favicon
#----------------------------
favicon: http://osausq2jb.bkt.clouddn.com/b.ico

#----------------------------


#----------------------------
# 是否开启分享
#----------------------------
share: true

#----------------------------
# 侧栏是否显示微博秀
#----------------------------
weibo_show:
  enable: false
  code: <iframe width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=1&ptype=1&speed=0&skin=5&isTitle=1&noborder=1&isWeibo=1&isFans=1&uid=3189093807&verifier=c1f8031e&dpc=1"></iframe>

#----------------------------
# 是否使用网易云跟帖
#----------------------------
gentie:
  enable: false
  productKey: c06bb9930e6f4b38a9997cb9bd17aba5

#----------------------------
# 是否开启云标签
#----------------------------
tagcloud: true

#----------------------------
# 友情链接
#----------------------------
friends:
  enable: true
  list:
    1:
      name: Search Console
      title: Google
      link: https://www.google.com/webmasters/tools/home?hl=zh-CN
    2:
      name: 百度站长工具
      title: baidu
      link: http://zhanzhang.baidu.com/?castk=LTE%3D
    3:
      name: 畅言
      title: 后台管理
      link: http://changyan.kuaizhan.com/

#----------------------------
# 头部链接
#----------------------------
head_links:
  enable: true
  list:
    sup:
      0:
        name: CSDN
        link: http://blog.csdn.net/u012743772
      1:
        name: Github
        link: https://github.com
      last:
        name: 百度统计
        link: http://tongji.baidu.com/web/welcome/login
    sub:
      sinaweibo:
        name: 简书
        link: http://www.jianshu.com/u/082645cc19c6
      qqweibo:
        name: 博客园
        link: http://www.cnblogs.com/xinxiucan
#----------------------------
# SEO
#----------------------------
SEO:
  keywords: XinXiuCan,java,hadoop,开发,测试,辛修灿,xinxiucan,spring
  description: 辛修灿个人博客

#----------------------------
# 百度分析
#----------------------------
baidu_analytics: true

#----------------------------
# 高亮样式
#----------------------------
highlight_theme: normal
#----------------------------
# CDN
#----------------------------
#CDN: //7xs305.com1.z0.glb.clouddn.com/
